# Generated by Django 2.0.5 on 2018-05-03 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='city',
            field=models.CharField(choices=[('KOCHI', 'kochi'), ('TRIVANDRUM', 'trivandrum'), ('KOTTAYAM', 'kottayam'), ('THRISSUR', 'thrissur'), ('KOZHIKODE', 'kozhikode')], max_length=20),
        ),
    ]
